# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Bandit
      run: |
        TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
        echo "Bandit report generated on: $TIMESTAMP" > post_traces/bandit
        bandit -r hw2_debugging.py rand.py -f txt -o post_traces/bandit || true
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.HW2_SECRET }}
      run: |
        git config --local user.email "bsse0635@iit.du.ac.bd"
        git config --local user.name "nazmul-md"
        git add -A
        git commit -m "Push from automated tools" || exit 0
        git push
