# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: autopep8 for automatically formats Python code to conform to the pep 8 style guide.
      run: |
        autopep8 -d --diff hw2_debugging.py
        autopep8 -d --diff rand.py
        autopep8 --aggressive --in-place hw2_debugging.py
        autopep8 --aggressive --in-place rand.py
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.HW2_SECRET }}
      run: |
        git config --local user.email "bsse0635@iit.du.ac.bd"
        git config --local user.name "nazmul-md"
        git add -A
        git commit -m "Push from automated tools" || exit 0
        git push
